name: Workflow Demo

on:
  schedule:
    - cron: '*/1 * * * *'  # every minute

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Echo ACCESS_ID
        run: echo $ACCESS_ID

